version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: python main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: python Test.py 
  deploy:
      working_directory: ~/circleci-python
    docker:
      -image: circleci/python:3.6.4
    steps:
      -checkout
      -run: echo "Deploying Successful" 
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      -deploy
          requires:
            - test   
          filters:
            branches:
              only: main   