version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python Test.py 

  deploy:
    docker:
      -image: cimg/python:3.11 
    steps:
      -checkout
      -run: echo "Deploying Successful" 
workflows:
  build_and_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      -deploy:    
          requires:
            - test   
          filters:
            branches:
              only: main   